algoritmo "Algoritmo CalculaValortotal"
// Função : Calcular valor total
// Autor : Danielle
// Data : 26/04/2022
// Seção de Declarações 
var
QTDE,VALOR,VT:real
inicio
escreval("Quantidade de peças: ")
leia(QTDE)
escreval("Valor das peças: ")
leia(VALOR)
// FIM DO PROCESSAMENTO
//PROCESSAMENTO
VT <- QTDE * VALOR
// FIM DO PROCESSAMENTO

//DADOS DE SAÍDA
escreval("O valor total é: ",VT)
fimalgoritmo
