algoritmo "CalculaMedia"
// Função :Calcular a media de 2 notas
// Autor :Danielle
// Data : 26/04/2022
// Seção de Declarações 
var
p1,p2,media:real
inicio
// DADOS DE ENTRADA
escreval("Entre com um valor para P1: ")
leia(p1)
escreval("Entre com um valor para P2: ")
leia(p2)
 //FIM DOS DADOS DE ENTRADA
 
 //PROCESSAMENTO
 media <- (p1+p2)/2
 //FIM DO PROCESSAMENTO
 
 //DADOS DE SAÍDA
 escreval("A Média do aluno é: ",media)
 //FIM DOS DADOS DE SAÍDA
 
fimalgoritmo
